allmodule = { 'DM_Input_10_Channel': {'Input_Gain': {'dataType': 'FLOAT',
                                        'datafield': '0~66dB and multiple of 6',
                                        'dec': 'N',
                                        'get': 'Y',
                                        'inc': 'N',
                                        'maxValue': 66,
                                        'minValue': 0,
                                        'set': 'Y',
                                        'subscribe': 'N',
                                        'toggle': 'N',
                                        'unsubscribe': 'N'},
                         'Input_Level': {'dataType': 'FLOAT',
                                         'datafield': '-100~12dB',
                                         'dec': 'Y',
                                         'get': 'Y',
                                         'inc': 'Y',
                                         'maxValue': 12,
                                         'minValue': -100,
                                         'set': 'Y',
                                         'subscribe': 'N',
                                         'toggle': 'N',
                                         'unsubscribe': 'N'},
                         'Input_Mute': {'dataType': 'BOOLEAN',
                                        'datafield': '0, 1',
                                        'dec': 'N',
                                        'get': 'Y',
                                        'inc': 'N',
                                        'maxValue': 1,
                                        'minValue': 0,
                                        'set': 'Y',
                                        'subscribe': 'N',
                                        'toggle': 'Y',
                                        'unsubscribe': 'N'},
                         'Invert': {'dataType': 'BOOLEAN',
                                    'datafield': '0, 1',
                                    'dec': 'N',
                                    'get': 'Y',
                                    'inc': 'N',
                                    'maxValue': 1,
                                    'minValue': 0,
                                    'set': 'Y',
                                    'subscribe': 'N',
                                    'toggle': 'Y',
                                    'unsubscribe': 'N'},
                         'Peak': {'dataType': 'STR',
                                  'datafield': None,
                                  'dec': 'N',
                                  'get': 'N',
                                  'inc': 'N',
                                  'maxValue': None,
                                  'minValue': None,
                                  'set': 'N',
                                  'subscribe': 'Y',
                                  'toggle': 'N',
                                  'unsubscribe': 'Y'},
                         'Phantom_Power': {'dataType': 'BOOLEAN',
                                           'datafield': '0, 1',
                                           'dec': 'N',
                                           'get': 'Y',
                                           'inc': 'N',
                                           'maxValue': 1,
                                           'minValue': 0,
                                           'set': 'Y',
                                           'subscribe': 'N',
                                           'toggle': 'Y',
                                           'unsubscribe': 'N'}},
 'DM_Output_6_Channel': {'FullScale': {'dataType': 'BOOLEAN',
                                       'datafield': '-31, 0, 6, 12, 18, 24',
                                       'dec': 'N',
                                       'get': 'Y',
                                       'inc': 'N',
                                       'maxValue': 24,
                                       'minValue': -31,
                                       'set': 'Y',
                                       'subscribe': 'N',
                                       'toggle': 'N',
                                       'unsubscribe': 'N'},
                         'Invert': {'dataType': 'BOOLEAN',
                                    'datafield': '0, 1',
                                    'dec': 'N',
                                    'get': 'Y',
                                    'inc': 'N',
                                    'maxValue': 1,
                                    'minValue': 0,
                                    'set': 'Y',
                                    'subscribe': 'N',
                                    'toggle': 'Y',
                                    'unsubscribe': 'N'},
                         'Output_Level': {'dataType': 'FLOAT',
                                          'datafield': '-100~0dB',
                                          'dec': 'Y',
                                          'get': 'Y',
                                          'inc': 'Y',
                                          'maxValue': 0,
                                          'minValue': -100,
                                          'set': 'Y',
                                          'subscribe': 'N',
                                          'toggle': 'N',
                                          'unsubscribe': 'N'},
                         'Output_Mute': {'dataType': 'BOOLEAN',
                                         'datafield': '0, 1',
                                         'dec': 'N',
                                         'get': 'Y',
                                         'inc': 'N',
                                         'maxValue': 1,
                                         'minValue': 0,
                                         'set': 'Y',
                                         'subscribe': 'N',
                                         'toggle': 'Y',
                                         'unsubscribe': 'N'}}}
